/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.haras.view.equino;

import br.com.haras.controller.EquinoController;
import br.com.haras.model.Equino;
import br.com.haras.view.FrMenu;
import br.com.haras.view.Tratamento.FrTratamento;
import br.com.haras.view.component.swing.ButtonOutLine;
import br.com.haras.view.component.swing.MyButton;
import br.com.haras.view.component.swing.MyTextField;
import br.com.haras.view.component.swing.TableDark;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author alice
 */
public class EquinoDialog extends javax.swing.JDialog {
    
    private PanelCoverEquino cover;
    private ButtonOutLine btnVoltar;
    private MyButton btnContinuar;
    private MigLayout layout;
    private PanelBuscaEq pnBuscaEq;
    private Equino equino;
    /**
     * Creates new form EquinoDialog
     */
    public EquinoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(1080,720);
        layout = new MigLayout("fill");
        bg.setLayout(layout);
        cover = new PanelCoverEquino();
        btnVoltar = new ButtonOutLine();
        btnContinuar = new MyButton();
        pnBuscaEq = new PanelBuscaEq();
        btnVoltar.setBackground(new Color(255,255,255));
        btnVoltar.setForeground(new Color(255,255,255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ev){
                new FrTratamento();
                dispose();   
            }
        });
        btnContinuar.setBackground(new Color(255,255,255));
        btnContinuar.setForeground(new Color(128,52,11));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ev){
                equino = pnBuscaEq.getEquinoSelecionado();
                dispose();   
            }
        });
        cover.add(btnContinuar, "center,bottom, pad -20 0 -20 0, w 20%, h 5%");
        cover.add(btnVoltar, "center,bottom, pad -20 0 -20 0, w 20%, h 5%");
        bg.add(cover,"width 20%, pos 1al 0 n 100%");
        bg.add(pnBuscaEq,"width 80%, pos 0al 0 n 100%");
       
        this.setVisible(true);
        
    }
    public Equino getEquinoSelecionado(){
        return this.equino;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquinoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquinoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquinoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquinoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EquinoDialog dialog = new EquinoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane bg;
    // End of variables declaration//GEN-END:variables
}
class PanelBuscaEq extends JPanel{
    private TableDark table;
    private Equino eqSelecionado;
    private EquinoController eqController= new EquinoController();
    private MyTextField nmEqSelecionado;
    public PanelBuscaEq(){
        
        this.setBackground(new Color(255,255,255));
        
        JPanel panelTitulo = new JPanel();
        panelTitulo.setLayout(new MigLayout("fill","[center]","push[center]push"));
        panelTitulo.setBackground(new Color (204, 83, 18));
        JLabel titulo = new JLabel("Gerenciar Raças");
        titulo.setFont(new Font("sansserif",3,36));
        titulo.setForeground(Color.white);
        panelTitulo.add(titulo);
      
        this.setLayout( new MigLayout("wrap","[center]","[top]push[]10[]10[]push[]push[]"));
        this.add(panelTitulo,"span,w 100%,h 15%, pad -10 -15 0 5, wrap");
        
        
        JLabel lblSelecionado = new JLabel("Equino Selecionado");
        lblSelecionado.setFont(new Font("sansserif",1,15));
        lblSelecionado.setForeground(new Color(74,37,20));
        nmEqSelecionado = new MyTextField();
        this.add(lblSelecionado,"center,split 2,gapright 20");
        this.add(nmEqSelecionado,"w 30%,center");
        
        table = new TableDark();
        this.atualizaTabelaEquino();
        JScrollPane scrollPane = new JScrollPane(table);
        table.fixTable(scrollPane);
        table.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    JTable target = (JTable) evt.getSource();
                    int row = target.getSelectedRow();
                    Equino eq =(Equino) table.getModel().getValueAt(row, -1);
                    eqSelecionado = eq;
                    nmEqSelecionado.setText(eqSelecionado.getNome());
                }
            }
        });
        this.add(scrollPane,"skip, w 95%, h 70%,pad 0 -15 10 -2");
    }
    public void atualizaTabelaEquino(){
        table.setModel(eqController.atualizarTabela());
    }
    public Equino getEquinoSelecionado(){
        return this.eqSelecionado;
    }
    
}
