/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.haras.view.equino;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author alice
 */
public class PanelCoverEquino extends javax.swing.JPanel {

    /**
     * Creates new form CoverEquino
     */
    public PanelCoverEquino() {
        initComponents();
        init();
    }
    private void init(){
        layout = new MigLayout("wrap,fill","[fill]","[top][]");
        setLayout(layout);
        setBackground(new Color (128,52,11));
        PanelImg img = new PanelImg(new ImageIcon(getClass().getResource("/imgs/historicoMedico/Logo.png")).getImage());
        
        add(img,"w 100%, h 30%, pad -10 -15 0 10 ");
       
    
    }
    private MigLayout layout;
    @Override
    protected void paintComponent(Graphics g) {
     Graphics2D g2 = (Graphics2D) g;
       ImageIcon img = null ;
       try{
           img = new ImageIcon(getClass().getResource("/imgs/por-do-sol.jpg"));
       }catch(Exception e){
           
       }
       
       if(img!=null){
           g2.drawImage(img.getImage(),0,0,getWidth(),getHeight(),this);
       }else{
            GradientPaint gradient = new GradientPaint(0,0,new Color(120,58,38),0,getHeight(), new Color(98,49,26));
            g2.setPaint(gradient);
            g2.fillRect(0, 0, getWidth(), getHeight());
       } 
       
       super.paintComponent(g);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
