/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.haras.view.component;

import br.com.haras.model.Anuncio;
import br.com.haras.model.Cliente;
import br.com.haras.model.Equino;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;


public class CardAnuncio extends javax.swing.JPanel {

    /**
     * Creates new form CardAnuncio
     * @param anuncio
     */
    private Anuncio anuncio;
    //MOCK


    public CardAnuncio(Anuncio anuncio) {
        initComponents();
        this.anuncio = anuncio;
        this.setLayout(new MigLayout("wrap","[center]","[]"));
        //TODO alterar para puxar o byte array da imagem
        this.setByteImage(this.anuncio.getEquino().getImagem());
        this.createDetalhes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgContainer = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        detalhes = new javax.swing.JPanel();

        javax.swing.GroupLayout imgContainerLayout = new javax.swing.GroupLayout(imgContainer);
        imgContainer.setLayout(imgContainerLayout);
        imgContainerLayout.setHorizontalGroup(
            imgContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        imgContainerLayout.setVerticalGroup(
            imgContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        detalhes.setBackground(new java.awt.Color(255, 255, 255));
        detalhes.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout detalhesLayout = new javax.swing.GroupLayout(detalhes);
        detalhes.setLayout(detalhesLayout);
        detalhesLayout.setHorizontalGroup(
            detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        detalhesLayout.setVerticalGroup(
            detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(detalhes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void setByteImage(byte[] imgBy){
        if(imgBy == null){
            return;
        }
        ImageIcon img = new ImageIcon(imgBy);
        Image imagemAtual = img.getImage().getScaledInstance(this.imgContainer.getWidth(), this.imgContainer.getHeight(), Image.SCALE_SMOOTH);
        this.image.setIcon(new ImageIcon(imagemAtual));
    }
    
    private void createDetalhes(){
        Equino equino = this.anuncio.getEquino();
        Cliente anunciante = this.anuncio.getAnunciante();
        this.detalhes.setLayout(new MigLayout("wrap","[center]","[]14[]"));
        
        JLabel animalName = new JLabel(equino.getNome());   
        animalName.setFont(new Font("Arial", Font.PLAIN, 14));
        this.detalhes.add(animalName);

        String[] valor = (this.anuncio.getVlAnuncio().toString()+"00").split("\\.");
        
        JLabel animalPrice = new JLabel("R$ "+valor[0] +","+valor[1].substring(0, 2));
        animalPrice.setFont(new Font("Arial", Font.BOLD, 16));
        this.detalhes.add(animalPrice);
        
        JLabel anuncianteName = new JLabel("Vendedor: "+anunciante.getNome());   
        anuncianteName.setFont(new Font("Arial", Font.PLAIN, 14));
        this.detalhes.add(animalName);
        
        
        JLabel info = new JLabel("Clique para mais detalhes");
        info.setFont(new Font("Arial", Font.PLAIN, 12));
        info.setForeground(Color.GRAY);
        this.detalhes.add(info);
        this.detalhes.revalidate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detalhes;
    private javax.swing.JLabel image;
    private javax.swing.JPanel imgContainer;
    // End of variables declaration//GEN-END:variables
}
