/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.haras.view;


import br.com.haras.controller.EventoController;
import br.com.haras.model.Evento;
import br.com.haras.model.enums.Status;
import br.com.haras.view.Raca.FrRaca;
import br.com.haras.view.Tratamento.FrTratamento;
import br.com.haras.view.equino.FrEquino;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author alice
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
        ImageIcon icone = new ImageIcon(getClass().getResource("/gui/CAVALO1.png"));
        this.setIconImage(icone.getImage());
        this.atualizarTabelaEventos();
        this.setSize(1080,720);
        this.getContentPane().setBackground(Color.decode("#D9C7B8"));
        this.setSituacaoComboBox();
        
        this.setVisible(true);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventosTable = new javax.swing.JTable();
        novoEventoBtn = new javax.swing.JButton();
        excluirEventoBtn = new javax.swing.JButton();
        situacaoCbb = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        propCadMenu = new javax.swing.JMenuItem();
        propFaturaMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(153, 102, 0));
        setBounds(new java.awt.Rectangle(0, 0, 1080, 720));
        setForeground(new java.awt.Color(153, 102, 0));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("FrMenu"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 36, 20));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eventos Futuros");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setName("EventosLbl"); // NOI18N
        jLabel1.setVerifyInputWhenFocusTarget(false);

        eventosTable.setBackground(new java.awt.Color(255, 248, 236));
        eventosTable.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        eventosTable.setForeground(new java.awt.Color(64, 36, 20));
        eventosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        eventosTable.setName("eventosTable"); // NOI18N
        eventosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(eventosTable);

        novoEventoBtn.setActionCommand("Novo");
        novoEventoBtn.setLabel("Novo evento");
        novoEventoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEventoBtnActionPerformed(evt);
            }
        });

        excluirEventoBtn.setLabel("Excluir evento");
        excluirEventoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirEventoBtnActionPerformed(evt);
            }
        });

        situacaoCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        situacaoCbb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                situacaoCbbItemStateChanged(evt);
            }
        });
        situacaoCbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                situacaoCbbMouseClicked(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(217, 199, 184));
        jMenuBar1.setForeground(new java.awt.Color(64, 36, 20));

        jMenu3.setText("Proprietários");

        propCadMenu.setText("Cadastrar");
        propCadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propCadMenuActionPerformed(evt);
            }
        });
        jMenu3.add(propCadMenu);

        propFaturaMenu.setText("Faturas");
        jMenu3.add(propFaturaMenu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Equinos");

        jMenu5.setText("Histórico Médico");

        jMenuItem4.setText("Consultar");
        jMenu5.add(jMenuItem4);

        jMenuItem8.setText("Registrar Doença");
        jMenuItem8.setToolTipText("");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Registrar Tipo Tratamento");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Registrar Tratamento");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenu4.add(jMenu5);

        jMenuItem5.setText("Registrar Equino");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem7.setText("Registrar Raça");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Compra e venda");

        jMenuItem12.setText("Registrar anúncio");
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Consultar Anúncios");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(situacaoCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(novoEventoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirEventoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(situacaoCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(novoEventoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(excluirEventoBtn)
                        .addGap(122, 122, 122))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void propCadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propCadMenuActionPerformed
        ClienteGUI cliente = new ClienteGUI();
        cliente.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_propCadMenuActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       FrEquino frEquino = new FrEquino();
       this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrRaca frRaca = new FrRaca();
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void novoEventoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoEventoBtnActionPerformed
        // TODO add your handling code here:
         
               EditEventoDialog evtDialog = new EditEventoDialog(this, rootPaneCheckingEnabled, "Novo evento",null,INSERIR);
               evtDialog.setVisible(true);
               System.out.println("fechou");
               this.atualizarTabelaEventos();
    }//GEN-LAST:event_novoEventoBtnActionPerformed

    private void eventosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventosTableMouseClicked
       if (evt.getClickCount() == 2) {     // to detect doble click events
               JTable target = (JTable)evt.getSource();
               int row = target.getSelectedRow(); // select a row
               Evento eventoConsulta = evtController.buscaEvento((int)eventosTable.getValueAt(row, 0));
               EditEventoDialog evtDialog = new EditEventoDialog(this, rootPaneCheckingEnabled, "Editando evento",eventoConsulta,ATUALIZAR);
               evtDialog.setVisible(true);
               System.out.println("fechou");
               this.atualizarTabelaEventos();
            }
    }//GEN-LAST:event_eventosTableMouseClicked

    private void excluirEventoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirEventoBtnActionPerformed
       try{
           int linha = eventosTable.getSelectedRow();
           int result = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o evento  " + eventosTable.getValueAt(linha, 1)+" ? ");
           if(result == JOptionPane.OK_OPTION){
            evtController.excluirEvento((int)(eventosTable.getValueAt(linha, 0)));
            this.atualizarTabelaEventos();
           }
       }catch(IndexOutOfBoundsException e){
           JOptionPane.showMessageDialog(rootPane, "Nenhum evento foi selecionado");
       }
    }//GEN-LAST:event_excluirEventoBtnActionPerformed

    private void situacaoCbbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_situacaoCbbItemStateChanged
        System.out.println(situacaoCbb.getSelectedItem());
    }//GEN-LAST:event_situacaoCbbItemStateChanged

    private void situacaoCbbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_situacaoCbbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_situacaoCbbMouseClicked

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new FrTratamento();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable eventosTable;
    private javax.swing.JButton excluirEventoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novoEventoBtn;
    private javax.swing.JMenuItem propCadMenu;
    private javax.swing.JMenuItem propFaturaMenu;
    private javax.swing.JComboBox<String> situacaoCbb;
    // End of variables declaration//GEN-END:variables
    private EventoController evtController = new EventoController();
    private static final int ATUALIZAR = 0;
    private static final int INSERIR = 1;
    
    private void atualizarTabelaEventos(){  
        eventosTable.setModel(evtController.atualizarTabela());
    }
     private void setSituacaoComboBox(){
         DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Status x : Status.values()){
            model.addElement(x.getDescricao());
        }
        situacaoCbb.setModel(model);
        situacaoCbb.setFocusable(false);
    }
//    private Evento retornaLinhaSelecionada(int linha){
//        int qtdColuna = eventosTable.getColumnCount();
//        Map<String,Object> dados = new HashMap<>();
//        for (int i= 0; i <qtdColuna; i++){
//            String nome =Normalizer.normalize( eventosTable.getColumnName(i), Normalizer.Form.NFD).replaceAll("[^\\p{ASCII}]", "");
//            nome = nome.toLowerCase();
//            Object valor = eventosTable.getValueAt(linha, i);
//            dados.put(nome,valor);
//        }
//        Evento evento = evtController.mapLinhaObjeto(dados);
//        return evento;
//    } 
    
}
